#!/usr/bin/env python3
"""Generate a learner-route authorization coverage matrix for Phase 2."""
from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ROUTER_DIR = REPO_ROOT / "app" / "api_v2_routers"

LEARNER_KEYWORDS = (
    "learner_id",
    "guardian_id",
    "parent",
    "consent",
    "popia",
    "diagnostic",
    "study",
    "lesson",
    "gamification",
    "assessment",
    "onboarding",
)

AUTHZ_MARKERS = (
    "require_learner_read_for_current_user",
    "require_learner_write_for_current_user",
    "require_learner_delete",
    "require_parent_or_admin",
    "get_current_user",
    "get_current_guardian_id",
    "get_current_user_id",
)

SAFE_BOUNDARY_DOCS = (
    "assessment_list_auth_boundary.md",
    "onboarding_questions_auth_boundary.md",
)


@dataclass(frozen=True)
class RouteRow:
    router: str
    method: str
    path: str
    function: str
    learner_scoped: bool
    authz_marker: str
    status: str


def _literal(value: ast.AST) -> str:
    if isinstance(value, ast.Constant) and isinstance(value.value, str):
        return value.value
    return ""


def _decorator_route(decorator: ast.AST) -> tuple[str, str] | None:
    call = decorator if isinstance(decorator, ast.Call) else None
    if call is None:
        return None

    func = call.func
    if not isinstance(func, ast.Attribute):
        return None
    if not isinstance(func.value, ast.Name) or func.value.id != "router":
        return None

    method = func.attr.upper()
    if method not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
        return None

    path = _literal(call.args[0]) if call.args else ""
    return method, path


def _function_source(source: str, node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    lines = source.splitlines()
    return "\n".join(lines[node.lineno - 1 : node.end_lineno or node.lineno])


def _is_learner_scoped(route_path: str, function_name: str, source: str) -> bool:
    haystack = f"{route_path}\n{function_name}\n{source}".lower()
    return any(keyword in haystack for keyword in LEARNER_KEYWORDS)


def _authz_marker(source: str) -> str:
    for marker in AUTHZ_MARKERS:
        if marker in source:
            return marker
    return ""


def collect_rows() -> list[RouteRow]:
    rows: list[RouteRow] = []

    for path in sorted(ROUTER_DIR.glob("*.py")):
        if path.name.startswith("__"):
            continue

        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))

        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue

            decorators = [_decorator_route(decorator) for decorator in node.decorator_list]
            routes = [decorator for decorator in decorators if decorator is not None]
            if not routes:
                continue

            fn_source = _function_source(source, node)
            marker = _authz_marker(fn_source)

            for method, route_path in routes:
                learner_scoped = _is_learner_scoped(route_path, node.name, fn_source)
                status = "covered"
                if learner_scoped and not marker:
                    status = "missing"
                elif not learner_scoped:
                    status = "not_learner_scoped"

                rows.append(
                    RouteRow(
                        router=path.name,
                        method=method,
                        path=route_path or "/",
                        function=node.name,
                        learner_scoped=learner_scoped,
                        authz_marker=marker or "-",
                        status=status,
                    )
                )

    return rows


def render(rows: list[RouteRow]) -> str:
    missing = [row for row in rows if row.status == "missing"]
    lines = [
        "# Learner Authorization Coverage Matrix",
        "",
        "Generated by `scripts/generate_learner_authz_matrix.py`.",
        "",
        "## Summary",
        "",
        f"- Routes inspected: {len(rows)}",
        f"- Missing learner authorization markers: {len(missing)}",
        "",
        "## Matrix",
        "",
        "| Router | Method | Path | Function | Learner-scoped | Marker | Status |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]

    for row in rows:
        lines.append(
            f"| `{row.router}` | `{row.method}` | `{row.path}` | `{row.function}` | "
            f"{'yes' if row.learner_scoped else 'no'} | `{row.authz_marker}` | `{row.status}` |"
        )

    if missing:
        lines.extend(["", "## Missing Coverage", ""])
        for row in missing:
            lines.append(f"- `{row.router}` `{row.method} {row.path}` via `{row.function}`")

    return "\n".join(lines) + "\n"


def main() -> int:
    rows = collect_rows()
    output = REPO_ROOT / "docs" / "security" / "learner_authz_matrix.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(rows), encoding="utf-8")
    print(f"Wrote {output.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
