#!/usr/bin/env python3
"""Generate a POPIA consent-gate inventory for learner-data routes."""
from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SEARCH_DIRS = (
    REPO_ROOT / "app" / "api_v2_routers",
    REPO_ROOT / "app" / "modules",
    REPO_ROOT / "app" / "services",
)

CONSENT_MARKERS = (
    "require_active_consent",
    "require_consent",
    "ConsentService",
    "get_active",
    "require_parental_consent",
)

LEARNER_DATA_KEYWORDS = (
    "learner_id",
    "learner",
    "diagnostic",
    "lesson",
    "assessment",
    "study_plan",
    "mastery",
    "progress",
    "gamification",
    "profile",
    "parent",
    "popia",
)


@dataclass(frozen=True)
class ConsentGateRow:
    path: str
    function: str
    learner_related: bool
    marker: str
    status: str


def _function_source(source: str, node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    lines = source.splitlines()
    return "\n".join(lines[node.lineno - 1 : node.end_lineno or node.lineno])


def _marker(source: str) -> str:
    for marker in CONSENT_MARKERS:
        if marker in source:
            return marker
    return ""


def _is_learner_related(name: str, source: str) -> bool:
    haystack = f"{name}\n{source}".lower()
    return any(keyword in haystack for keyword in LEARNER_DATA_KEYWORDS)


def collect_rows() -> list[ConsentGateRow]:
    rows: list[ConsentGateRow] = []

    for search_dir in SEARCH_DIRS:
        if not search_dir.exists():
            continue

        for file_path in sorted(search_dir.rglob("*.py")):
            if file_path.name.startswith("__"):
                continue
            if file_path.name.startswith("test_") or file_path.name.endswith("_test.py"):
                continue

            try:
                source = file_path.read_text(encoding="utf-8")
                tree = ast.parse(source, filename=str(file_path))
            except SyntaxError:
                continue

            parents = {
                child: parent
                for parent in ast.walk(tree)
                for child in ast.iter_child_nodes(parent)
            }

            for node in ast.walk(tree):
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                if isinstance(parents.get(node), (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue

                fn_source = _function_source(source, node)
                learner_related = _is_learner_related(node.name, fn_source)
                marker = _marker(fn_source)
                status = "covered" if learner_related and marker else "missing" if learner_related else "not_learner_related"

                rows.append(
                    ConsentGateRow(
                        path=str(file_path.relative_to(REPO_ROOT)),
                        function=node.name,
                        learner_related=learner_related,
                        marker=marker or "-",
                        status=status,
                    )
                )

    return rows


def render(rows: list[ConsentGateRow]) -> str:
    missing = [row for row in rows if row.status == "missing"]
    lines = [
        "# POPIA Consent Gate Inventory",
        "",
        "Generated by `scripts/generate_consent_gate_inventory.py`.",
        "",
        "## Summary",
        "",
        f"- Functions inspected: {len(rows)}",
        f"- Learner-related functions without local consent marker: {len(missing)}",
        "",
        "## Inventory",
        "",
        "| File | Function | Learner-related | Marker | Status |",
        "| --- | --- | --- | --- | --- |",
    ]

    for row in rows:
        lines.append(
            f"| `{row.path}` | `{row.function}` | {'yes' if row.learner_related else 'no'} | `{row.marker}` | `{row.status}` |"
        )

    if missing:
        lines.extend(["", "## Candidate Missing Consent Gates", ""])
        for row in missing:
            lines.append(f"- `{row.path}` `{row.function}`")

    return "\n".join(lines) + "\n"


def main() -> int:
    rows = collect_rows()
    output = REPO_ROOT / "docs" / "security" / "popia_consent_gate_inventory.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(rows), encoding="utf-8")
    print(f"Wrote {output.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
