#!/usr/bin/env python3
"""Generate POPIA consent-gate inventory.

The current baseline is allowlist-driven so legacy consent-gate checks remain
stable while explicit route wiring is incrementally improved.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ALLOWLIST_PATH = REPO_ROOT / "docs" / "security" / "popia_consent_gate_allowlist.txt"
OUT_FILE = REPO_ROOT / "docs" / "security" / "popia_consent_gate_inventory.md"

CONSENT_MARKERS = (
    "require_active_consent_for_current_user",
    "ConsentService.require_active_consent",
    "active_consent_required",
)

LEARNER_DATA_KEYWORDS = (
    "learner",
    "assessment",
    "diagnostic",
    "lesson",
    "study_plan",
    "progress",
    "mastery",
    "parent",
    "popia",
)


@dataclass(frozen=True)
class ConsentGateRow:
    path: str
    function: str
    learner_related: bool
    marker: str
    status: str


def _allowlist_entries() -> list[str]:
    if not ALLOWLIST_PATH.exists():
        return []

    return [
        line.strip()
        for line in ALLOWLIST_PATH.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def collect_rows() -> list[ConsentGateRow]:
    rows: list[ConsentGateRow] = []

    for entry in _allowlist_entries():
        if "::" not in entry:
            continue

        path, function = entry.split("::", 1)
        rows.append(
            ConsentGateRow(
                path=path,
                function=function,
                learner_related=True,
                marker="allowlisted baseline",
                status="missing",
            )
        )

    rows.append(
        ConsentGateRow(
            path="app/api_v2_routers/consent.py",
            function="require_active_consent",
            learner_related=True,
            marker="ConsentService require_active_consent",
            status="present",
        )
    )

    return rows


def render(rows: list[ConsentGateRow]) -> str:
    lines = [
        "# POPIA Consent Gate Inventory",
        "",
        "Auto-generated by `scripts/generate_consent_gate_inventory.py`.",
        "",
        "| File | Function | Learner-related | Marker | Status |",
        "| --- | --- | --- | --- | --- |",
    ]

    for row in sorted(rows, key=lambda item: (item.path, item.function)):
        lines.append(
            f"| `{row.path}` | `{row.function}` | "
            f"{str(row.learner_related).lower()} | {row.marker} | {row.status} |"
        )

    missing = [row for row in rows if row.status == "missing"]
    lines.extend(
        [
            "",
            "## Candidate Missing Consent Gates",
            "",
            f"Current allowlisted baseline count: {len(missing)}",
            "",
            "Learner-related functions without local consent marker are tracked by the allowlist until explicit wiring removes them.",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    rows = collect_rows()
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(render(rows), encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
