#!/usr/bin/env python3
"""Generate a deterministic route inventory for the canonical V2 runtime."""
from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path

from fastapi import FastAPI
from fastapi.routing import APIRoute

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_APP = "app.api_v2:app"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "route_inventory.md"

LEGACY_PREFIXES = (
    "/api/v1",
    "/v1",
    "/api/legacy",
    "/legacy",
)

REQUIRED_OPERATIONAL_ROUTES = (
    "/",
    "/health",
    "/ready",
    "/metrics",
    "/v2/health/deep",
    "/docs",
    "/redoc",
    "/openapi.json",
)

REQUIRED_V2_PREFIXES = (
    "/api/v2",
    "/v2",
)

REQUIRED_ROUTER_FRAGMENTS = (
    "/auth",
    "/learners",
    "/lessons",
    "/study-plans",
    "/diagnostics",
    "/gamification",
    "/onboarding",
    "/parents",
    "/billing",
    "/consent",
    "/popia",
    "/jobs",
    "/system",
)


RouteRow = tuple[str, str, str, str, str]


def _ensure_repo_root_on_path() -> None:
    repo_root = str(REPO_ROOT)
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)


def load_app(spec: str) -> FastAPI:
    """Load a FastAPI app from a ``module:attribute`` import string."""
    _ensure_repo_root_on_path()

    if ":" not in spec:
        raise ValueError("App spec must use the format 'module:attribute'.")

    module_name, attribute_name = spec.split(":", 1)
    module = importlib.import_module(module_name)
    app = getattr(module, attribute_name)

    if not isinstance(app, FastAPI):
        raise TypeError(f"{spec!r} did not resolve to a FastAPI application.")

    return app


def _route_rows(app: FastAPI) -> list[RouteRow]:
    rows: list[RouteRow] = []

    for route in app.routes:
        path = getattr(route, "path", "")
        name = getattr(route, "name", "")

        if isinstance(route, APIRoute):
            methods = ",".join(sorted(route.methods or []))
            endpoint = f"{route.endpoint.__module__}.{route.endpoint.__name__}"
            include_in_schema = "yes" if route.include_in_schema else "no"
            rows.append((path, methods, name, include_in_schema, endpoint))
            continue

        methods = ",".join(sorted(getattr(route, "methods", []) or []))
        endpoint = type(route).__name__
        rows.append((path, methods, name, "no", endpoint))

    return sorted(rows, key=lambda row: (row[0], row[1], row[2]))


def _legacy_route_rows(rows: list[RouteRow]) -> list[RouteRow]:
    return [row for row in rows if row[0].startswith(LEGACY_PREFIXES)]


def _present_paths(rows: list[RouteRow]) -> set[str]:
    return {row[0] for row in rows}


def _missing_operational_routes(rows: list[RouteRow]) -> list[str]:
    paths = _present_paths(rows)
    return [path for path in REQUIRED_OPERATIONAL_ROUTES if path not in paths]


def _missing_router_fragments(rows: list[RouteRow]) -> list[str]:
    paths = _present_paths(rows)
    missing: list[str] = []

    for prefix in REQUIRED_V2_PREFIXES:
        for fragment in REQUIRED_ROUTER_FRAGMENTS:
            expected_prefix = f"{prefix}{fragment}"
            if not any(path == expected_prefix or path.startswith(f"{expected_prefix}/") for path in paths):
                missing.append(expected_prefix)

    return missing


def render_route_inventory(app: FastAPI, app_spec: str = DEFAULT_APP) -> str:
    """Render the route inventory markdown document."""
    rows = _route_rows(app)
    legacy_rows = _legacy_route_rows(rows)
    missing_operational = _missing_operational_routes(rows)
    missing_fragments = _missing_router_fragments(rows)
    paths = _present_paths(rows)

    lines = [
        "# EduBoost V2 Route Inventory",
        "",
        "> Generated by `scripts/generate_route_inventory.py`.",
        "",
        "## Runtime",
        "",
        f"- Canonical runtime: `{app_spec}`",
        f"- Application title: `{app.title}`",
        f"- Application version: `{app.version}`",
        f"- Total route entries: `{len(rows)}`",
        "",
        "## Contract Checks",
        "",
        f"- Legacy route prefixes present in canonical runtime: `{'yes' if legacy_rows else 'no'}`",
        f"- Missing operational routes: `{', '.join(missing_operational) if missing_operational else 'none'}`",
        f"- Missing V2 router fragments: `{', '.join(missing_fragments) if missing_fragments else 'none'}`",
        "",
        "## Required Operational Routes",
        "",
        "| Route | Status |",
        "| --- | --- |",
    ]

    for route in REQUIRED_OPERATIONAL_ROUTES:
        status = "present" if route in paths else "missing"
        lines.append(f"| `{route}` | {status} |")

    lines.extend([
        "",
        "## Required V2 Router Fragments",
        "",
        "| Prefix | Fragment | Status |",
        "| --- | --- | --- |",
    ])

    for prefix in REQUIRED_V2_PREFIXES:
        for fragment in REQUIRED_ROUTER_FRAGMENTS:
            expected_prefix = f"{prefix}{fragment}"
            status = (
                "present"
                if any(path == expected_prefix or path.startswith(f"{expected_prefix}/") for path in paths)
                else "missing"
            )
            lines.append(f"| `{prefix}` | `{fragment}` | {status} |")

    lines.extend([
        "",
        "## Legacy Exclusion",
        "",
        "The canonical runtime must not expose V1 or legacy-prefixed routes.",
        "",
        "Forbidden prefixes:",
        "",
    ])

    for prefix in LEGACY_PREFIXES:
        lines.append(f"- `{prefix}`")

    lines.extend([
        "",
        "The archived compatibility shim `app.legacy.api.main:app` resolves to the canonical V2 app and must not mount V1 routes as an import side effect.",
        "",
        "## Canonical Route Table",
        "",
        "| Path | Methods | Name | In OpenAPI | Endpoint |",
        "| --- | --- | --- | --- | --- |",
    ])

    for path, methods, name, include_in_schema, endpoint in rows:
        lines.append(
            f"| `{path}` | `{methods or '-'}` | `{name or '-'}` | {include_in_schema} | `{endpoint}` |"
        )

    lines.append("")
    return "\n".join(lines)


def write_inventory(output_path: Path, content: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def check_inventory(output_path: Path, content: str) -> bool:
    if not output_path.exists():
        return False
    return output_path.read_text(encoding="utf-8") == content


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate docs/route_inventory.md from the canonical V2 FastAPI app."
    )
    parser.add_argument(
        "--app",
        default=DEFAULT_APP,
        help=f"FastAPI app import string. Default: {DEFAULT_APP}",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output path. Default: {_display_path(DEFAULT_OUTPUT)}",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated route inventory differs from the committed file.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_path = args.output.resolve()
    app = load_app(args.app)
    content = render_route_inventory(app, app_spec=args.app)

    if args.check:
        if check_inventory(output_path, content):
            return 0

        print(
            f"Route inventory drift detected. Regenerate with: "
            f"python3 scripts/generate_route_inventory.py --output {_display_path(output_path)}",
            file=sys.stderr,
        )
        return 1

    write_inventory(output_path, content)
    print(f"Wrote route inventory to {_display_path(output_path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
