#!/usr/bin/env python3
"""Inspect learner-scoped route candidates for Phase 2 authorization wiring."""
from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCAN_ROOTS = (
    REPO_ROOT / "app",
    REPO_ROOT / "tests",
)

LEARNER_PATTERNS = (
    "learner_id",
    "learner-id",
    "{learner_id}",
    "learner",
    "learners",
)

ROUTER_DECORATOR_RE = re.compile(r"@\w+\.(get|post|put|patch|delete)\((?P<args>.*)")
PATH_LITERAL_RE = re.compile(r"['\"](?P<path>/[^'\"]*)['\"]")


@dataclass(frozen=True)
class LearnerRouteCandidate:
    file: str
    line: int
    method: str
    path: str
    function: str
    reason: str


@dataclass(frozen=True)
class LearnerReference:
    file: str
    line: int
    text: str


def _relative(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _iter_python_files(scan_roots: tuple[Path, ...]) -> list[Path]:
    files: list[Path] = []
    for root in scan_roots:
        if not root.exists():
            continue
        files.extend(
            path
            for path in root.rglob("*.py")
            if "__pycache__" not in path.parts and ".venv" not in path.parts
        )
    return sorted(files)


def _function_name_at_or_after(lines: list[str], start_index: int) -> str:
    for line in lines[start_index : start_index + 8]:
        stripped = line.strip()
        if stripped.startswith("async def ") or stripped.startswith("def "):
            return stripped.split("def ", maxsplit=1)[1].split("(", maxsplit=1)[0]
    return "unknown"


def _decorator_path(text: str) -> str | None:
    match = PATH_LITERAL_RE.search(text)
    if not match:
        return None
    return match.group("path")


def _has_learner_signal(text: str) -> bool:
    lowered = text.lower()
    return any(pattern.lower() in lowered for pattern in LEARNER_PATTERNS)


def find_route_candidates(files: list[Path]) -> list[LearnerRouteCandidate]:
    candidates: list[LearnerRouteCandidate] = []

    for path in files:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()

        for index, line in enumerate(lines):
            match = ROUTER_DECORATOR_RE.search(line.strip())
            if not match:
                continue

            decorator_window = "\n".join(lines[index : index + 4])
            route_path = _decorator_path(decorator_window)
            if not route_path:
                continue

            function_window = "\n".join(lines[index : index + 12])
            if not (_has_learner_signal(route_path) or _has_learner_signal(function_window)):
                continue

            candidates.append(
                LearnerRouteCandidate(
                    file=_relative(path),
                    line=index + 1,
                    method=match.group(1).upper(),
                    path=route_path,
                    function=_function_name_at_or_after(lines, index),
                    reason="route path or handler window references learner scope",
                )
            )

    return sorted(candidates, key=lambda item: (item.file, item.line, item.method, item.path))


def find_references(files: list[Path]) -> list[LearnerReference]:
    references: list[LearnerReference] = []

    for path in files:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()

        for index, line in enumerate(lines):
            if _has_learner_signal(line):
                references.append(
                    LearnerReference(
                        file=_relative(path),
                        line=index + 1,
                        text=line.strip()[:240],
                    )
                )

    return sorted(references, key=lambda item: (item.file, item.line))


def render_markdown(
    route_candidates: list[LearnerRouteCandidate],
    references: list[LearnerReference],
) -> str:
    lines = [
        "# Learner Route Authorization Inspection",
        "",
        "> Generated by `scripts/inspect_learner_routes.py`.",
        "",
        "## Learner-Scoped Route Candidates",
        "",
        "| File | Line | Method | Path | Function | Reason |",
        "| --- | ---: | --- | --- | --- | --- |",
    ]

    if route_candidates:
        for candidate in route_candidates:
            lines.append(
                f"| `{candidate.file}` | {candidate.line} | `{candidate.method}` | "
                f"`{candidate.path}` | `{candidate.function}` | {candidate.reason} |"
            )
    else:
        lines.append("| — | — | — | — | — | no route candidates found |")

    lines.extend(
        [
            "",
            "## Learner References",
            "",
            "| File | Line | Text |",
            "| --- | ---: | --- |",
        ]
    )

    for reference in references[:200]:
        safe_text = reference.text.replace("|", "\\|")
        lines.append(f"| `{reference.file}` | {reference.line} | `{safe_text}` |")

    if len(references) > 200:
        lines.append(f"| — | — | `{len(references) - 200} additional references omitted` |")

    lines.extend(
        [
            "",
            "## Next Step",
            "",
            "Use the first stable learner-scoped read route as the pilot endpoint for `require_learner_read(...)` wiring.",
            "",
        ]
    )

    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Inspect likely learner-scoped routes for authorization wiring."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "docs" / "security" / "learner_route_authorization_inspection.md",
    )
    parser.add_argument("--json", action="store_true", help="Emit JSON instead of Markdown.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    files = _iter_python_files(DEFAULT_SCAN_ROOTS)
    candidates = find_route_candidates(files)
    references = find_references(files)

    if args.json:
        print(
            json.dumps(
                {
                    "route_candidates": [asdict(candidate) for candidate in candidates],
                    "references": [asdict(reference) for reference in references],
                },
                indent=2,
                sort_keys=True,
            )
        )
        return 0

    content = render_markdown(candidates, references)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote learner route authorization inspection to {args.output}")
    print(f"Route candidates: {len(candidates)}")
    print(f"Learner references: {len(references)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
