#!/usr/bin/env python3
from __future__ import annotations

import ast
import re
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AUTH = ROOT / "app/api_v2_routers/auth.py"
SERVICE = ROOT / "app/services/auth_application_service.py"
IMPL = ROOT / "app/services/auth_lifecycle_impl.py"
REPORT = ROOT / "docs/release/auth_lifecycle_service_ownership_report.md"
BLOCKER = ROOT / "docs/release/auth_lifecycle_service_ownership_blockers.md"

HELPER_PREFIX = "_auth_lifecycle_legacy_"
SERVICE_MARKER = "# code_951_990_auth_service_owned_lifecycle_methods"


def _write_blocker(lines: list[str]) -> None:
    BLOCKER.write_text(
        "\n".join(
            [
                "# Auth Lifecycle Service Ownership Blocker",
                "",
                f"Generated at: `{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}`",
                "",
                *lines,
                "",
            ]
        ),
        encoding="utf-8",
    )


def _function_method_name(name: str) -> str | None:
    if not name.startswith(HELPER_PREFIX) or not name.endswith("_impl"):
        return None
    return name[len(HELPER_PREFIX) : -len("_impl")]


def _top_level_imports(tree: ast.Module, source_lines: list[str]) -> list[str]:
    imports: list[str] = []
    excluded_modules = {
        "app.services.auth_application_service",
        "app.api_v2_deps.auth_service",
    }

    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            module = node.module if isinstance(node, ast.ImportFrom) else None
            if module in excluded_modules:
                continue
            start = node.lineno - 1
            end = node.end_lineno or node.lineno
            text = "\n".join(source_lines[start:end])
            if "from __future__ import annotations" in text:
                continue
            imports.append(text)

    seen: set[str] = set()
    unique: list[str] = []
    for item in imports:
        if item not in seen:
            unique.append(item)
            seen.add(item)
    return unique


def _strip_depends_defaults(signature_text: str) -> str:
    return re.sub(r"\s*=\s*Depends\([^)]*\)", "", signature_text)


def _extract_and_rename_helpers(source: str) -> tuple[str, list[tuple[str, str]]]:
    tree = ast.parse(source)
    lines = source.splitlines()
    helpers: list[tuple[str, str, int, int]] = []

    for node in tree.body:
        if isinstance(node, (ast.AsyncFunctionDef, ast.FunctionDef)):
            method = _function_method_name(node.name)
            if method is None:
                continue
            start = node.lineno - 1
            end = node.end_lineno or node.lineno
            helpers.append((node.name, method, start, end))

    extracted: list[tuple[str, str]] = []
    new_lines = list(lines)

    for old_name, method, start, end in sorted(helpers, key=lambda item: item[2], reverse=True):
        block = "\n".join(lines[start:end])
        new_name = f"{method}_impl"
        block = re.sub(rf"\bdef\s+{re.escape(old_name)}\b", f"def {new_name}", block, count=1)
        block = _strip_depends_defaults(block)
        block = re.sub(r",?\s*auth_service\s*:\s*AuthApplicationService\s*(?:=\s*[^,\)\n]+)?", "", block)
        block = re.sub(r",\s*\)", ")", block)
        extracted.append((method, block))
        del new_lines[start:end]

    auth_without_helpers = "\n".join(new_lines) + "\n"
    auth_without_helpers = re.sub(r"\n{4,}", "\n\n\n", auth_without_helpers)
    return auth_without_helpers, sorted(extracted, key=lambda item: item[0])


def _build_impl_module(imports: list[str], extracted: list[tuple[str, str]]) -> str:
    body: list[str] = [
        '"""Service-owned auth lifecycle implementations.',
        "",
        "Generated by code_951_990. This module owns lifecycle logic that was",
        "temporarily preserved as private helpers in app.api_v2_routers.auth.",
        '"""',
        "",
    ]
    body.extend(imports)
    body.extend(
        [
            "",
            "",
            "async def _maybe_await(value):",
            "    if hasattr(value, '__await__'):",
            "        return await value",
            "    return value",
            "",
        ]
    )

    exported: list[str] = []
    for method, block in extracted:
        body.extend(["", block, ""])
        exported.append(f"{method}_impl")

    body.extend(["", "__all__ = [", *[f"    '{name}'," for name in exported], "]", ""])
    return "\n".join(body)


def _patch_service_file(methods: list[str]) -> None:
    text = SERVICE.read_text(encoding="utf-8") if SERVICE.exists() else ""

    # Remove code_911 dynamic assignment block if present.
    marker = "# code_911_950_auth_lifecycle_methods"
    marker_index = text.find(marker)
    if marker_index != -1:
        text = text[:marker_index].rstrip() + "\n"

    marker_index = text.find(SERVICE_MARKER)
    if marker_index != -1:
        text = text[:marker_index].rstrip() + "\n"

    if "class AuthApplicationServiceError" not in text and "AuthApplicationServiceError" not in text:
        text += "\n\nclass AuthApplicationServiceError(RuntimeError):\n    pass\n"

    addition: list[str] = [
        "",
        SERVICE_MARKER,
        "from app.services import auth_lifecycle_impl as _auth_lifecycle_impl",
        "",
        "",
        "async def _auth_service_call_impl(self, impl_name: str, **kwargs):",
        "    kwargs.pop('legacy_impl', None)",
        "    kwargs.pop('auth_service', None)",
        "    impl = getattr(_auth_lifecycle_impl, impl_name)",
        "    result = impl(**kwargs)",
        "    if hasattr(result, '__await__'):",
        "        return await result",
        "    return result",
        "",
    ]

    for method in methods:
        impl_name = f"{method}_impl"
        addition.extend(
            [
                "",
                f"async def _auth_service_{method}(self, **kwargs):",
                f"    return await self._auth_service_call_impl('{impl_name}', **kwargs)",
                "",
                f"AuthApplicationService.{method} = _auth_service_{method}",
            ]
        )

    if "create_dev_session" not in methods:
        addition.extend(
            [
                "",
                "async def _auth_service_create_dev_session(self, **kwargs):",
                "    if hasattr(_auth_lifecycle_impl, 'create_dev_session_impl'):",
                "        return await self._auth_service_call_impl('create_dev_session_impl', **kwargs)",
                "    raise AuthApplicationServiceError('create_dev_session_impl is not available')",
                "",
                "AuthApplicationService.create_dev_session = _auth_service_create_dev_session",
            ]
        )

    text = text.rstrip() + "\n" + "\n".join(addition) + "\n"
    ast.parse(text)
    SERVICE.write_text(text, encoding="utf-8")


def _patch_auth_wrappers(text: str) -> str:
    # Remove legacy_impl arguments from route delegates.
    text = re.sub(r"\n\s*legacy_impl=_auth_lifecycle_legacy_[A-Za-z0-9_]+_impl,", "", text)
    text = re.sub(r"\n\s*auth_service=auth_service,", "", text)
    text = re.sub(r"\n\s*\)\n\n\n", "\n    )\n\n", text)
    return text


def main() -> int:
    if not AUTH.exists():
        _write_blocker(["Missing `app/api_v2_routers/auth.py`."])
        return 1
    if not SERVICE.exists():
        _write_blocker(["Missing `app/services/auth_application_service.py`. Run code_871_910/code_911_950 first."])
        return 1

    source = AUTH.read_text(encoding="utf-8")
    tree = ast.parse(source)
    source_lines = source.splitlines()

    auth_without_helpers, extracted = _extract_and_rename_helpers(source)
    if not extracted:
        # Idempotent pass: if already migrated, still generate a report and exit cleanly.
        if IMPL.exists() and "_auth_lifecycle_legacy_" not in source:
            REPORT.write_text(
                "\n".join(
                    [
                        "# Auth Lifecycle Service Ownership Report",
                        "",
                        f"Generated at: `{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}`",
                        "",
                        "**Status:** already migrated",
                        "",
                    ]
                ),
                encoding="utf-8",
            )
            print("Auth lifecycle helpers already migrated")
            return 0
        _write_blocker(["No `_auth_lifecycle_legacy_*_impl` helpers found in auth.py."])
        return 1

    imports = _top_level_imports(tree, source_lines)
    impl_text = _build_impl_module(imports, extracted)
    ast.parse(impl_text)

    auth_without_helpers = _patch_auth_wrappers(auth_without_helpers)
    ast.parse(auth_without_helpers)

    methods = [method for method, _block in extracted]
    IMPL.write_text(impl_text, encoding="utf-8")
    AUTH.write_text(auth_without_helpers, encoding="utf-8")
    _patch_service_file(methods)

    report_lines = [
        "# Auth Lifecycle Service Ownership Report",
        "",
        f"Generated at: `{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}`",
        "",
        "**Status:** implemented",
        "",
        "## Migrated lifecycle implementations",
        "",
        *[f"- `{method}` -> `app.services.auth_lifecycle_impl.{method}_impl`" for method in methods],
        "",
        "## Auth router state",
        "",
        "- Private `_auth_lifecycle_legacy_*_impl` helpers removed from `auth.py`.",
        "- Route wrappers call `AuthApplicationService` directly.",
        "- Business logic has been moved into service-owned implementation module.",
        "",
        "## Remaining debt",
        "",
        "- Add success-path HTTP tests using controlled test repositories/database fixtures.",
        "- Remove implementation-module import surface once method-local service code is stable.",
        "",
    ]
    REPORT.write_text("\n".join(report_lines), encoding="utf-8")
    if BLOCKER.exists():
        BLOCKER.unlink()

    print(f"Wrote {IMPL.relative_to(ROOT)}")
    print(f"Patched {AUTH.relative_to(ROOT)}")
    print(f"Patched {SERVICE.relative_to(ROOT)}")
    print(f"Wrote {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
